      - uses: actions/upload-artifact@v4
        with:
          name: ipatool-windows-arm64.exe
          path: ipatool-${{ needs.get_version.outputs.version }}-windows-arm64.exe
          if-no-files-found: error

      - uses: actions/upload-artifact@v4
        with:
          name: ipatool-windows-amd64.exe
          path: ipatool-${{ needs.get_version.outputs.version }}-windows-amd64.exe
          if-no-files-found: error

      - uses: actions/upload-artifact@v4
        with:
          name: ipatool-linux-arm64
          path: ipatool-${{ needs.get_version.outputs.version }}-linux-arm64
          if-no-files-found: error

      - uses: actions/upload-artifact@v4
        with:
          name: ipatool-linux-amd64
          path: ipatool-${{ needs.get_version.outputs.version }}-linux-amd64
          if-no-files-found: error

      - uses: actions/upload-artifact@v4
        with:
          name: ipatool-macos-arm64
          path: ipatool-${{ needs.get_version.outputs.version }}-macos-arm64
          if-no-files-found: error

      - uses: actions/upload-artifact@v4
        with:
          name: ipatool-macos-amd64
          path: ipatool-${{ needs.get_version.outputs.version }}-macos-amd64
          if-no-files-found: error
